from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from citagro import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = patterns('',
	#Vista Index
    url(r'^$', views.ingresar, name ='ingresar'),
	url(r'^logout$', views.logout_view, name="logout"),
	url(r'^/$',views.main,name = "index"),
	
	#Vistas Administrador citagro
	url(r'^superAdministrador/$', views.VistaAdministradorCitagro, name='administradorCitagro'),
	url(r'^superAdministrador/administradores/$', views.ListaAdministradores, name='administradores'),
	url(r'^superAdministrador/creaAdministrador/$', views.creaAdministrador, name='creaAdministrador'),
	url(r'^superAdministrador/password_change/$',views.password_change, name='password_change'),
	url(r'^superAdministrador/cambiarUsuario/$',views.cambiaUsuario, name='cambiarUsuario'),

	
	#Vistas Usuario administrador
	url(r'^administrador/$', views.VistaAdministrador, name='administrador'),
	url(r'^configuracion/$', views.VistaConfiguracion, name='configuracion'),
	url(r'^administrador/tecnicos/$', views.ListaTecnicosAdministrador, name='tecnicos'),
	url(r'^crearParcela/(.*)/$', views.crearParcela, name='crearParcela'),
	url(r'^administrador/explotaciones/$', views.ListaExplotaciones, name='explotaciones'),
	url(r'^administrador/explotacion/(?P<id_Explotacion>\d+)/$', views.AdministradorExplotacionId, name='explotacion'),
	url(r'^administrador/creaTecnico/$', views.creaTecnico, name='creaTecnico'),
	url(r'^administrador/modificaTecnico/(?P<id_Tecnico>\d+)/$', views.ModificaTecnico, name='modificaTecnico'),
	url(r'^administrador/creaExplotacion/$',views.creaExplotacion, name='creaExplotacion'),
	url(r'^administrador/nuevaMaquina/$',views.creaMaquina, name='creaMaquina'),
	url(r'^administrador/asignaExplotacion/(?P<id_Explotacion>\d+)/$',views.AsignaUsuario, name='asignaUsuario'),
	url(r'^administrador/tecnicosExplotacion/(?P<id_Explotacion>\d+)/$',views.VistaUsuarioExplotacion, name='tecnicosExplotacion'),
	url(r'^administrador/eliminaUsuarioExplotacion/(?P<pk>\d+)/$',views.EliminarUsuario.as_view(), name='eliminaUsuario'),
	url(r'^administrador/password_change/$',views.password_change, name='password_change2'),
    url(r'^administrador/cambiarUsuario/$',views.cambiaUsuario, name='cambiarUsuario2'),
	url(r'^administrador/maquinas_Y_Equipos/(?P<id_Explotacion>\d+)/$',views.ListaMaquinaria, name='maquinas'),
	url(r'^administrador/maquinas_Y_Equipos/(?P<id_Explotacion>\d+)/Nueva_Maquina/$',views.creaMaquina, name='nuevaMaquina'),
	url(r'^administrador/maquinas_Y_Equipos/Eliminar_Maquina/(?P<pk>\d+)/$',views.EliminarMaquina.as_view(), name='eliminaMaquina'),
	url(r'^administrador/maquinas_Y_Equipos/$',views.MaquinariaUsuario, name='maquinasUsuario'),
	url(r'^administrador/analisis/(?P<id_Analisis>\d+)/$',views.VistaAnalisis, name='analisis'),
	url(r'^administrador/aplicacion/(?P<id_Aplicacion>\d+)/$',views.VistaAplicacion, name='aplicacion'),
	url(r'^administrador/operacion/(?P<id_Operacion>\d+)/$',views.VistaOperacion, name='operacion'),
	url(r'^administrador/Datos_Climaticos/(?P<id_Explotacion>\d+)/$',views.datosClimaticos, name='datosClimaticos'),
	url(r'^administrador/Datos_Climaticos/(?P<id_Explotacion>\d+)/Nuevo_dato_climatologico/$',views.creaDatosClimaticos, name='nuevoDatoClimatico'),
    url(r'^administrador/muestreo/(?P<id_Muestra>\d+)/$',views.VistaMuestreo, name='muestreo'),
	url(r'^analisis/archivo/(?P<id_documento>\d+)/$',views.pdf_view, name='pdf'),

	#Vistas Usuario tecnico
	url(r'^tecnico/$', views.VistaTecnico, name='tecnico'),
	url(r'^tecnicoExplotacion/(.*)$', views.VistaTecnicoExplotacion, name='tecnicoExplotacion'),
	url(r'^EditaInput/(.*)$', views.EditaInput, name='EditaInput'),
	url(r'^tecnicoCultivo/(.*)$', views.VistaTecnicoCultivo, name='tecnico'),
    url(r'^tecnico/explotacion/(?P<id_Explotacion>\d+)/$', views.TecnicoExplotacionId, name='explotacionTecnico'),
    url(r'^tecnico/explotacion/(.*)/$', views.TecnicoExplotacionIdUHC, name='TecnicoExplotacionIdUHC'),
	url(r'^informeUHC/(.*)/$',views.generaInformePDF, name='generaPdf'),
	url(r'^tecnico/password_change/$',views.password_change, name='password_change3'),
    url(r'^tecnico/cambiarUsuario/$',views.cambiaUsuario, name='cambiarUsuario3'),
    url(r'^tecnico/analisis/(?P<id_Analisis>\d+)/$',views.VistaAnalisisTecnico, name='analisisTecnico'),
	url(r'^tecnico/operacion/(?P<id_Operacion>\d+)/$',views.VistaOperacionTecnico, name='operacionTecnico'),
	url(r'^tecnico/muestreo/(?P<id_Muestra>\d+)/$',views.VistaTecnicoMuestreo, name='muestreoTecnico'),
	url(r'^tecnico/aplicacion/(?P<id_Aplicacion>\d+)/$',views.VistaAplicacionTecnico, name='aplicacionTecnico'),
	
	#API
	url(r'^api/perfil/$', views.PerfilList.as_view()),
    url(r'^api/perfil/(?P<pk>[0-9]+)/$', views.PerfilDetail.as_view()),
	url(r'^api/usuarios/$', views.UsuariosList.as_view()),
    url(r'^api/usuarios/(?P<pk>[0-9]+)/$', views.UsuariosDetail.as_view()),
	url(r'^api/administradores/$', views.AdministradorList.as_view()),
    url(r'^api/administradores/(?P<pk>[0-9]+)/$', views.AdministradorDetail.as_view()),
	url(r'^api/tecnicos/$', views.TecnicoList.as_view()),
    url(r'^api/tecnicos/(?P<pk>[0-9]+)/$', views.TecnicoDetail.as_view()),
	url(r'^api/Inputoperacion/$', views.InputoperacionList.as_view()),
    url(r'^api/Inputoperacion/(?P<pk>[0-9]+)/$', views.InputoperacionDetail.as_view()),
	url(r'^api/Tiposoperacion/$', views.TiposoperacionList.as_view()),
    url(r'^api/Tiposoperacion/(?P<pk>[0-9]+)/$', views.TiposoperacionDetail.as_view()),
	url(r'^api/explotaciones/$', views.ExplotacionList.as_view()),
    url(r'^api/explotaciones/(?P<pk>[0-9]+)/$', views.ExplotacionDetail.as_view()),
	url(r'^api/datosClimaticos/$', views.DatosClimaticosList.as_view()),
    url(r'^api/datosClimaticos/(?P<pk>[0-9]+)/$', views.DatosClimaticosDetail.as_view()),
	url(r'^api/maquinaria/$', views.MaquinariaList.as_view()),
    url(r'^api/maquinaria/(?P<pk>[0-9]+)/$', views.MaquinariaDetail.as_view()),
	url(r'^api/provincias/$', views.ProvinciaList.as_view()),
    url(r'^api/provincias/(?P<pk>[0-9]+)/$', views.ProvinciaDetail.as_view()),
	url(r'^api/municipios/$', views.MunicipioList.as_view()),
    url(r'^api/municipios/(?P<pk>[0-9]+)/$', views.MunicipioDetail.as_view()),
	url(r'^api/aplicadores/$', views.AplicadorList.as_view()),
    url(r'^api/aplicadores/(?P<pk>[0-9]+)/$', views.AplicadorDetail.as_view()),
	url(r'^api/uhcs/$', views.UHCList.as_view()),
    url(r'^api/uhcs/(?P<pk>[0-9]+)/$', views.UHCDetail.as_view()),
	url(r'^api/analisis/$', views.AnalisisList.as_view()),
    url(r'^api/analisis/(?P<pk>[0-9]+)/$', views.AnalisisDetail.as_view()),
	url(r'^api/aplicaciones/$', views.AplicacionList.as_view()),
    url(r'^api/aplicaciones/(?P<pk>[0-9]+)/$', views.AplicacionDetail.as_view()),
	url(r'^api/productos/$', views.ProductoList.as_view()),
    url(r'^api/productos/(?P<pk>[0-9]+)/$', views.ProductoDetail.as_view()),
	url(r'^api/parcelas/$', views.ParcelaList.as_view()),
    url(r'^api/parcelas/(?P<pk>[0-9]+)/$', views.ParcelaDetail.as_view()),
	url(r'^api/parcelauhc/$', views.ParcelauhcList.as_view()),
    url(r'^api/parcelauhc/(?P<pk>[0-9]+)/$', views.ParcelauhcDetail.as_view()),
	url(r'^api/cultivo/$', views.CultivoList.as_view()),
    url(r'^api/cultivo/(?P<pk>[0-9]+)/$', views.CultivoDetail.as_view()),
	url(r'^api/cultivoexplotacion/$', views.CultivoexplotacionList.as_view()),
    url(r'^api/cultivoexplotacion/(?P<pk>[0-9]+)/$', views.CultivoexplotacionDetail.as_view()),
	url(r'^api/usuarioExplotacion/$', views.UsuarioExplotacionList.as_view()),
    url(r'^api/usuarioExplotacion/(?P<pk>[0-9]+)/$', views.UsuarioExplotacionDetail.as_view()),
	url(r'^api/maquinaExplotacion/$', views.MaquinaExplotacionList.as_view()),
    url(r'^api/maquinaExplotacion/(?P<pk>[0-9]+)/$', views.MaquinaExplotacionDetail.as_view()),
	url(r'^api/operaciones/$', views.OperacionList.as_view()),
    url(r'^api/operaciones/(?P<pk>[0-9]+)/$', views.OperacionDetail.as_view()),
	url(r'^api/operaciones/poda/$', views.op_podaList.as_view()),
    url(r'^api/operaciones/poda/(?P<pk>[0-9]+)/$', views.op_podaDetail.as_view()),
	url(r'^api/operaciones/labores/$', views.op_laboresList.as_view()),
    url(r'^api/operaciones/labores/(?P<pk>[0-9]+)/$', views.op_laboresDetail.as_view()),
	url(r'^api/operaciones/fertilizacion/$', views.op_fertilizacionList.as_view()),
    url(r'^api/operaciones/fertilizacion/(?P<pk>[0-9]+)/$', views.op_fertilizacionDetail.as_view()),
	url(r'^api/operaciones/riego/$', views.op_riegoList.as_view()),
    url(r'^api/operaciones/riego/(?P<pk>[0-9]+)/$', views.op_riegoDetail.as_view()),
	url(r'^api/operaciones/recoleccion/$', views.op_recoleccionList.as_view()),
    url(r'^api/operaciones/recoleccion/(?P<pk>[0-9]+)/$', views.op_recoleccionDetail.as_view()),
	url(r'^api/muestras/$', views.MuestreoList.as_view()),
    url(r'^api/muestras/(?P<pk>[0-9]+)/$', views.MuestreoDetail.as_view()),
	url(r'^api/muestras/fenologia/$', views.muestra_fenologiaList.as_view()),
    url(r'^api/muestras/fenologia/(?P<pk>[0-9]+)/$', views.muestra_fenologiaDetail.as_view()),
	url(r'^api/muestras/insectos/$', views.muestra_insetosList.as_view()),
    url(r'^api/muestras/insectos/(?P<pk>[0-9]+)/$', views.muestra_insetosDetail.as_view()),
	url(r'^api/muestras/trampas/$', views.muestra_trampasList.as_view()),
    url(r'^api/muestras/trampas/(?P<pk>[0-9]+)/$', views.muestra_trampasDetail.as_view()),
	url(r'^api/muestras/brotes/$', views.muestra_brotesList.as_view()),
    url(r'^api/muestras/brotes/(?P<pk>[0-9]+)/$', views.muestra_brotesDetail.as_view()),
	url(r'^api/muestras/zeuzera/$', views.muestra_zeuzeraList.as_view()),
    url(r'^api/muestras/zeuzera/(?P<pk>[0-9]+)/$', views.muestra_zeuzeraDetail.as_view()),
	url(r'^api/muestras/enfermedades/$', views.muestra_enfermedadesList.as_view()),
    url(r'^api/muestras/enfermedades/(?P<pk>[0-9]+)/$', views.muestra_enfermedadesDetail.as_view()),
	
)
urlpatterns = format_suffix_patterns(urlpatterns)
